field: 5a97eecc-eb31-420d-a6a7-db8f228243a2 # Inhalt
fieldLayouts:
  ec19f600-f0cc-4cac-8d10-a2c44c0078ef:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6d790ee1-baaa-4798-a32f-7658fdb87f9b # Externe URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8d2b5f6-a450-42f6-9911-0ad683a56f83
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 82aedd8f-e6b7-43ec-9182-d26f3eca60f2 # Seite
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cdc71c8e-4bf0-4ef4-aa5c-0b0d3c7f50e0
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1fce1f93-751a-4c9a-b930-e49a604eebba # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12309215-25c0-4de1-b57d-e1680620fd88
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b30fe9ee-2f09-4790-bef3-a0595c9885de # Hintergrund
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823ccee7-235e-4a93-a8aa-b6e5442483e8
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 33a18723-fb41-47f2-82e4-7939578344d8
        userCondition: null
fields:
  1fce1f93-751a-4c9a-b930-e49a604eebba: # Label
    columnSuffix: uvkwxvoz
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: null
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  6d790ee1-baaa-4798-a32f-7658fdb87f9b: # Externe URL
    columnSuffix: fqesdysy
    contentColumnType: text
    fieldGroup: null
    handle: externalUrl
    instructions: null
    name: 'Externe URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  82aedd8f-e6b7-43ec-9182-d26f3eca60f2: # Seite
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonEntry
    instructions: null
    name: Seite
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:6a67bde5-479e-4cf2-9c86-2560ff522e41' # Seiten
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  b30fe9ee-2f09-4790-bef3-a0595c9885de: # Hintergrund
    columnSuffix: kifslnzi
    contentColumnType: char
    fieldGroup: null
    handle: bg
    instructions: null
    name: Hintergrund
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - '0'
            -
              - value
              - '0'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '1'
            -
              - value
              - '1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: button
name: Button
sortOrder: 3
