field: 5a97eecc-eb31-420d-a6a7-db8f228243a2 # Inhalt
fieldLayouts:
  bb4fbddd-38ee-4619-8077-fd76dda7ca39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b643d6e-123d-4476-a205-964684585195 # Spenden Widget anzeigen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b22c82cc-a8ec-4fad-bed0-a98351070597
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 691738d5-51b4-49fe-b2b3-984d56275f86
        userCondition: null
fields:
  4b643d6e-123d-4476-a205-964684585195: # Spenden Widget anzeigen
    columnSuffix: fwrklorl
    contentColumnType: boolean
    fieldGroup: null
    handle: showDonationWidget
    instructions: null
    name: 'Spenden Widget anzeigen'
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: donate
name: 'Spenden Widget'
sortOrder: 6
