field: c6e90878-c245-4504-a9e1-abae79f2f1ed # Abbinder (Inhalt mit weißem Hintergrund)
fieldLayouts:
  7b3112fc-9bec-4a27-8496-e13fee70bfa2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ab2c8dd0-a79e-4448-ab00-25842c4fed9e # Überschrift
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 594f484f-ccee-41c9-991e-9fa01f2c706d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 30e68226-a4d7-42a0-a7f9-56ee3b7223a7
        userCondition: null
fields:
  ab2c8dd0-a79e-4448-ab00-25842c4fed9e: # Überschrift
    columnSuffix: linafwqw
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: null
    name: Überschrift
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: headline
name: Überschrift
sortOrder: 1
