field: c6e90878-c245-4504-a9e1-abae79f2f1ed # Abbinder (Inhalt mit weißem Hintergrund)
fieldLayouts:
  3ecab2fa-af28-4d9a-8651-59e532c38fd1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 036fcb8f-39f9-4b5e-aba3-7b71248c8991 # Quelle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a5e7da8-6a36-4381-b02a-4ed4a2041d69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 395fae88-6d5c-4b5f-b94b-357424076f95
        userCondition: null
fields:
  036fcb8f-39f9-4b5e-aba3-7b71248c8991: # Quelle
    columnSuffix: zsbvyxvs
    contentColumnType: text
    fieldGroup: null
    handle: src
    instructions: null
    name: Quelle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: iFrame
name: iFrame
sortOrder: 4
