field: c6e90878-c245-4504-a9e1-abae79f2f1ed # Abbinder (Inhalt mit weißem Hintergrund)
fieldLayouts:
  942c989e-a8a2-4a7e-a463-0d4b4459de7c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: b8697113-fc95-4b85-8286-98023dc09b60 # Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88ab0db7-a2bc-4528-a3e0-0ebdf44fb5c0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 943b0ce6-567d-4545-b3e1-3b60310de721
        userCondition: null
fields:
  b8697113-fc95-4b85-8286-98023dc09b60: # Logos
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: logos
    instructions: null
    name: Logos
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:00f8646b-6022-4e0d-98ea-4a1769ba9d3a' # Logos
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:9c6cb273-e941-4c08-a2fe-daca1623031f' # Dateien
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:00f8646b-6022-4e0d-98ea-4a1769ba9d3a' # Logos
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: logos
name: Logos
sortOrder: 3
