field: 5a97eecc-eb31-420d-a6a7-db8f228243a2 # Inhalt
fieldLayouts:
  ed8553e0-f06b-4644-9ee5-c28a30236e57:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 57a7333c-602e-4cd4-a1a0-c91c621f7b91 # Elemente
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2f61091-f1a7-4419-b7a8-f1dbea499a7e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42a7ccf9-cff4-4390-ae74-946a852f6d71 # Anker ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 641540c7-1dc5-46f2-9122-8f72d9d4d28c
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 4ed45227-e24a-4382-9a77-1ac020c8270e
        userCondition: null
fields:
  42a7ccf9-cff4-4390-ae74-946a852f6d71: # Anker ID
    columnSuffix: czeirvkv
    contentColumnType: text
    fieldGroup: null
    handle: anchorID
    instructions: null
    name: 'Anker ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  57a7333c-602e-4cd4-a1a0-c91c621f7b91: # Elemente
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sliderEntries
    instructions: null
    name: Elemente
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      sources:
        - 'section:c65bd544-5e1e-4c9e-83bc-422f66ab24e8' # Slides
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: slider
name: Slider
sortOrder: 7
