field: c6e90878-c245-4504-a9e1-abae79f2f1ed # Abbinder (Inhalt mit weißem Hintergrund)
fieldLayouts:
  be22bf22-09d3-4b3b-af9e-4ef19f890746:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4e8964da-a75d-478c-ab7b-a962fcbbac5f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7656a963-2ada-4489-ba36-480cce00e0de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6fdc22f6-e1a4-40d7-86c8-40c5377840b2
        userCondition: null
fields:
  4e8964da-a75d-478c-ab7b-a962fcbbac5f: # Text
    columnSuffix: dmlifcwq
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      ckeConfig: 498dc256-c446-4458-9ef9-17c54d6c601e # Einfach
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: text
name: Text
sortOrder: 2
