field: 5a97eecc-eb31-420d-a6a7-db8f228243a2 # Inhalt
fieldLayouts:
  cd9c0f4e-7f38-4364-984b-9819f9d9e336:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cc4293be-9e3d-4424-9654-9429ba67e524 # Vimeo ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f683462f-6abf-416d-a6a7-eaa73a375b5a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76d84189-b1ab-4b72-a350-2b277da5f42d
        userCondition: null
fields:
  cc4293be-9e3d-4424-9654-9429ba67e524: # Vimeo ID
    columnSuffix: jjahwebi
    contentColumnType: string(255)
    fieldGroup: null
    handle: vimeoId
    instructions: null
    name: 'Vimeo ID'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: video
name: Video
sortOrder: 8
