fieldLayouts:
  0274c07e-233b-463f-a32d-4e195de728fe:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3a12485e-569e-4485-b91f-f25f480501f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5a97eecc-eb31-420d-a6a7-db8f228243a2 # Inhalt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d42961bc-d1ba-407b-a13d-4958b7b8c21e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 44ab3aa6-824a-4ea5-9728-91b3db4ac1c3
            userCondition: null
        name: Inhalt
        uid: 6a63de8d-0794-43d3-b3e4-c9724826a5ee
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53b22fe6-fce8-4938-a03e-ae5b1639ca61 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66492d77-242d-4ea7-b0c2-4bbcbe0e1aef
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bbacbdd4-2815-4e2e-a5a3-83405e4d794f
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 6a67bde5-479e-4cf2-9c86-2560ff522e41 # Seiten
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
