fieldLayouts:
  3dea6d05-27da-4eb1-b008-726256e67210:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5444632c-753a-40b9-9a05-daa110a2cd7b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 964d7f16-757d-4192-8340-9ddfce04ec18 # Zahlen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 823eed15-582f-42cc-9be7-e8696a39abe2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 423833a3-ef68-41b8-aacd-c03cb7abbac0 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddbd1a26-5d90-4a8b-94d6-3e9df8792124
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: d55ebb12-b5bf-4f52-b00e-ec6ad663d9f4
        userCondition: null
handle: numbers
hasTitleField: true
name: Zahlen
section: c65bd544-5e1e-4c9e-83bc-422f66ab24e8 # Slides
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
