fieldLayouts:
  5751681e-645c-49a6-adcd-01eef9524497:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3218bc2c-8bc1-48c6-964c-8a164ead369a
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 613087b0-2bfd-48a4-979a-44cfe93f603a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae3d9c08-973e-4ba3-92b9-00575fa43af4 # Externe URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d76dcb4c-c131-4a4e-a8ba-06eec32c9c53
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 81000002-7d05-4722-86fe-be3019eb8ce8
        userCondition: null
fs: logos
handle: logos
name: Logos
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
