columnSuffix: null
contentColumnType: string
fieldGroup: f06f4efc-7d95-436a-bab4-de48b3bd1379 # Inhalt
handle: contentMatrix
instructions: null
name: Inhalt
searchable: false
settings:
  contentTable: '{{%matrixcontent_contentmatrix}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
