columnSuffix: ssysyibl
contentColumnType: text
fieldGroup: 926d9948-ec4a-4748-b4c3-c46afcabe74d # Spendenwidget
handle: donationHeadline
instructions: null
name: Überschrift
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
