columnSuffix: uneebdrz
contentColumnType: text
fieldGroup: 926d9948-ec4a-4748-b4c3-c46afcabe74d # Spendenwidget
handle: donationBottomText
instructions: null
name: Text
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 498dc256-c446-4458-9ef9-17c54d6c601e # Einfach
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
