columnSuffix: null
contentColumnType: string
fieldGroup: 1a351ce4-7ddf-45eb-9151-61228d9ab658 # Einstellungen
handle: footerNavigation
instructions: null
name: 'Footer Navigation'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:6a67bde5-479e-4cf2-9c86-2560ff522e41' # Seiten
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
