columnSuffix: ilsxrpmt
contentColumnType: text
fieldGroup: 1a351ce4-7ddf-45eb-9151-61228d9ab658 # Einstellungen
handle: phone
instructions: null
name: Telefon
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
