columnSuffix: azfiddni
contentColumnType: text
fieldGroup: 8a32bcd6-82c1-4060-a7c4-bbbe04fa1b42 # Allgemein
handle: quote
instructions: null
name: Zitat
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: 498dc256-c446-4458-9ef9-17c54d6c601e # Einfach
  columnType: text
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
