defaultPlacement: end
enableVersioning: true
handle: home
name: Startseite
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9363f036-dc6e-47a2-abde-d8f71980c397: # VBRG Opferhilfefonds
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
