defaultPlacement: end
enableVersioning: true
handle: pages
name: Seiten
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9363f036-dc6e-47a2-abde-d8f71980c397: # VBRG Opferhilfefonds
    enabledByDefault: true
    hasUrls: true
    template: _pages/default.twig
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 2cc5fa89-c206-41f7-941f-ef85bc00e6be
type: structure
