defaultPlacement: end
enableVersioning: true
handle: settings
name: Einstellungen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primäre eintrag Seite'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9363f036-dc6e-47a2-abde-d8f71980c397: # VBRG Opferhilfefonds
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
